FROM apache/airflow:2.9.3-python3.11

COPY requirements-train.txt /requirements-train.txt
COPY requirements-airflow.txt /requirements-airflow.txt
RUN pip install --no-cache-dir -r /requirements-airflow.txt
